language: python

python:
    - "2.7"

# Setup anaconda
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip 
    - git clone git@github.com:JulienPeloton/s4cmb.git
    - cd s4cmb
    - python setup.py install

# Tests are inside modules (doctest)
script:
    - python instrument/hardware.py
    - python instrument/scanning_strategy.py
