language: python

python:
    - "2.7"

addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libopenmpi-dev
            - openmpi-bin

install:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt

script:
    - python -c 'from mpi4py import MPI'
